seed: 42
prefix_len: 8
batch_size: 8
dropout: 0.3
use_layernorm: true
weight_decay: 0.1
test_size: 0.1
model_name: t5-base
data_dir: data/dataset
checkpoint_dir: checkpoints
results_dir: results
stage1:
  epochs: 50
  lr: 0.02419702903241395
stage2:
  epochs: 30
  projection_lr: 9.522559201484311e-05
  lm_lr: 0.0005095918332423143
lr_search:
  s1_lr: [1.0e-2, 1.0e-1]
  s2_proj_lr: [1.0e-5, 1.0e-3]
  s2_lm_lr: [5.0e-6, 1.0e-2]
