seed: 42
prefix_len: 8
batch_size: 8
dropout: 0.3
weight_decay: 0.1
test_size: 0.1
model_name: t5-base
data_dir: data/dataset
checkpoint_dir: checkpoints
results_dir: results
stage1:
  epochs: 30
  lr: 0.00999227982107514
stage2:
  epochs: 30
  projection_lr: 1.1660426548937395e-05
  lm_lr: 9.787864007753567e-05
