"""Score LP-MusicCaps predictions on the thesis test split (main env).

The captions were generated by lp_musiccaps_generate.py in the separate torch-1.13
venv; here we reuse evaluate.compute_metrics (same 10 metrics + FENSE as every
other row) so LP-MusicCaps drops into the reference-comparison table. Writes the
metrics file at the exact path reference_comparison.py expects
(results/reference/lp_music_caps/lp_music_caps_metrics_lp_music_caps.json).
"""
import argparse
import json
from pathlib import Path

from evaluate import compute_metrics


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pred",
                    default="results/reference/lp_music_caps/predictions/lp_music_caps_predictions_pretrain.json")
    ap.add_argument("--name", default="lp_music_caps")
    ap.add_argument("--out", default=None,
                    help="Defaults to results/reference/<name>/<name>_metrics_<name>.json")
    args = ap.parse_args()

    pred = json.loads(Path(args.pred).read_text())
    refs = [p["reference"] for p in pred["predictions"]]
    hyps = [p["hypothesis"] for p in pred["predictions"]]
    print(f"Scoring {len(refs)} predictions ({pred.get('framework')}) ...")

    metrics = compute_metrics(refs, hyps)
    for k, v in metrics.items():
        print(f"  {k}: {v:.4f}")

    out = Path(args.out) if args.out else (
        Path("results/reference") / args.name / f"{args.name}_metrics_{args.name}.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "model": pred.get("model", "lp-music-caps/pretrain"),
        "stage": "reference",
        "framework": pred.get("framework", "pretrain"),
        "num_samples": len(refs),
        "num_failed": pred.get("num_failed", 0),
        "gen_kwargs": pred.get("gen_kwargs", {}),
        "metrics": metrics,
        "predictions": pred["predictions"],
    }, indent=2))
    print(f"Saved -> {out}")


if __name__ == "__main__":
    main()
